@endpoint=http://127.0.0.1:8080

### user 생성
POST {{endpoint}}/api/users/ HTTP/1.1
Content-Type: application/json

{
    "name" :"csh",
    "email" : "cshee8508@gmail.com",
    "password" : "12345678"
}

### email 인증
POST {{endpoint}}/api/users/email-verify?signupVerifyToken=3a18e8d0-ceef-11ed-860b-9121332645cc HTTP/1.1
Content-Type: application/json

### login
POST {{endpoint}}/api/users/login HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInN1YiI6MSwibmFtZSI6IkFETUlOIiwiaWF0IjoxNjExMTk4MDM4LCJleHAiOjE2MTE4MDI4Mzh9.BFihUnQEQeazY-pwAXzafYOI6adNodDEe1oREdLFOWY
Content-Type: application/json

{
   "email" : "cshee8508@gmail.com",
    "password" : "12345678"
}


### get user info
GET {{endpoint}}/api/users/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImNzaCIsImVtYWlsIjoiY3NoZWU4NTA4QGdtYWlsLmNvbSIsImlhdCI6MTY4MTEyOTg3MSwiZXhwIjoxNjgxMjE2MjcxLCJhdWQiOiJleGFtcGxlLmNvbSIsImlzcyI6ImV4YW1wbGUuY29tIn0.k77A2AL3Wl8IZ1H646GHhbfAbl5QcJL88XZK4aY5lig
Content-Type: application/json
